#!/usr/bin/python3

# iplog

import datetime
import requests
x = requests.get('https://ifconfig.me/ip')
ip =x.text

print(ip)

f = open("/var/log/iplog" ,"r").readlines()

for x in f:
    iplist = x.split()
    ips=iplist[2]
    if ips == ip:
        print(ips + "  >>>  BAD IP :: " + iplist[0])

# Dates & Write
x = datetime.datetime.now()

dates= x.strftime("\n%x %X ")

d = open("/var/log/iplog", "a")
#d = open("tmp-iplog", "a")
d.write(dates + ip) 
